### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by graberj** [CentralLabFacilities/openpose_ros#2]
I cloned the directory into my catkin_ws/src directory, then ran `$ catkin_make`, which resulted in the following CMake Error: 

---

-- +++ processing catkin package: 'openpose_ros_msgs'
-- ==> add_subdirectory(openpose_ros/openpose_ros_msgs)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Generating .msg files for action openpose_ros_msgs/GetCrowdAttributesWithPose /home/mda-linux/catkin_ws/src/openpose_ros/openpose_ros_msgs/action/GetCrowdAttributesWithPose.action
CMake Error at /opt/ros/kinetic/share/genmsg/cmake/genmsg-extras.cmake:263 (message):
  Messages depends on unknown pkg: gender_and_age_msgs (Missing
  'find_package(gender_and_age_msgs)'?)
Call Stack (most recent call first):
  openpose_ros/openpose_ros_msgs/CMakeLists.txt:36 (generate_messages)

-- Configuring incomplete, errors occurred!
See also "/home/mda-linux/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/mda-linux/catkin_ws/build/CMakeFiles/CMakeError.log".
Makefile:6648: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

---
Will I be able to simply remove the lines within the CMakeLists and package files that call for GetCrowdAttributesWithPose (I don't need it), or is the solution not that simple?

**Comment by DavidPL1** [comment]
Hi, sorry for the long wait,
if you haven't solved the problem yet, you could remove the usage of GetCrowdAttributesWithPose messages in the code, but the easier option is to clone the [gender and age](https://github.com/CentralLabFacilities/face_gender_age_detection) package to your workspace and build again
